monitor:
  name: 7T
  width: 69  # width of monitor (in cm)
  distance: 225  # distance of participant from monitor (in cm)
  gamma: 1  # specific value for gamma correction
  verbose: True

window:
  size: [1920, 1080]
  units: pix
  screen: 1

eyetracker:
  address: '100.1.1.1'
  dot_size: 0.1  # in deg
  options:
    calibration_type: HV9
    calibration_area_proportion: 0.4 0.4
    validation_area_proportion: 0.4 0.4

stimuli:
  instruction_text: 'Press a button whenever the fixation mark changes color'
  pretrigger_text: ''
  fix_radius: 3
  fix_color: [1, -1, 1]
  inner_fix_linewidth: 3
  outer_fix_linewidth: 1
  fix_barrier_linewidth: 5
  stim_size_pixels: 1080 # the full height of a HD screen, likely to be used
  aperture_radius: 1 # defined in fraction of stimulus radius
  refresh_rate: 120 # this is just a suggestion; the code doesn't depend on it
  bg_stim_h5file: 'toon_stims_512.h5'
  bg_stim_url: 'https://figshare.com/ndownloader/files/44497559'
  bg_stim_refresh_time: 0.0666666666667 # in s, 15Hz
  bar_refresh_times: [0.0666666666667] # in s, should be acquisition TR for a standard stepping bar design, Dumoulin-style
  #bar_directions: [-1, 225, 315, -1, 45, 135, -1, -1, 135, 45, -1, 315, 225, -1]
  #add 45 to all directions to make it consistent with the bar direction in the stimuli except -1 which is the blank
  bar_directions: [270, 0, -1, 90, 180, -1, -1, 180, 90, -1, 0, 270]

  
  bar_widths: [0.16666667] # relative to total bg stimulus size, [0.125] would be a 'standard' Dumoulin-style pRF design
  bar_blank_duration: 0.0333333333333
  bar_blank_interval: 0.1333333333333
  shrink_factor: 0.7
  fix_perimeter_size: 0.325
  fix_perimeter_smooth: 0.3
  movie_size_pix: [1536,1080]

design:
  offset_ifi_duration: 2.0
  minimal_ifi_duration: 2.0
  gaussian_ifi_sd: 0
  exponential_ifi_mean: 2.5
  start_duration: 24.0 # 24 for a standard Dumoulin-style pRF design fMRI experiment
  end_duration: 24.0 # 24 for a standard Dumoulin-style pRF design fMRI experiment
  bar_duration: 24.0 # 30 for a standard Dumoulin-style pRF design fMRI experiment
  blank_duration: 16.0 # 16 for a standard Dumoulin-style pRF design fMRI experiment
  ttl_trigger_delay: 0.001 # delay after setting parallel port status for triggers
  ttl_trigger_bar: 2 # trigger code
  ttl_trigger_blank: 3 # trigger code
  ttl_trigger_start: 5 # trigger code

various:
  text_width: 500
  text_height: 40
  text_position_x: 0
  text_position_y: 100
  buttons: ['b', 'j', 'k', 'l', 'semicolon']
  save_screenshot: True
  screenshot_rate_hz: 15

paths:
  stimuli_path: "/Users/shufanzhang/AOT_stimuli/rescaled_final"
